language: cpp

notifications:
  email: false

dist: bionic

os:
  - linux
  #- osx

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sw
    #- $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - clang-9
    
#before_cache:
  #- brew cleanup
  
before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  - if [[ $LINUX ]]; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-linux-client.tar.gz; fi
  - if [[ $OSX ]]  ; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-macos-client.tar.gz; fi
  - tar -xvf sw.tar.gz
  - chmod 755 sw
  
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - if [[ $OSX ]]  ; then brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/llvm.rb; fi
  - if [[ $OSX ]]  ; then brew install bison; fi
  - if [[ $OSX ]]  ; then brew install flex; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/bison/bin:$PATH"; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/flex/bin:$PATH"; fi
    
script:
  - ./sw -checks-st -v build
