language: cpp

notifications:
  email: false

#sudo: required
dist: xenial

os:
  #- linux
  - osx

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sw
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    #- postgresql
    #- postgresql-server-dev-10
  #homebrew:
    #packages:
    #- llvm@7
    #- bison
    #- flex
    
#before_cache:
  #- brew cleanup
  
before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  - if [[ $LINUX ]]; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-linux-client.tar.gz; fi
  - if [[ $OSX ]]  ; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-macos-client.tar.gz; fi
  - tar -xvf sw.tar.gz
  
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - if [[ $OSX ]]  ; then brew install llvm; fi
  - if [[ $OSX ]]  ; then brew install bison; fi
  - if [[ $OSX ]]  ; then brew install flex; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/bison/bin:$PATH"; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/flex/bin:$PATH"; fi
  
script:
  #- true
  - ./sw build
