language: cpp

notifications:
  email: false

dist: bionic

os:
  - linux
  #- osx

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sw
    #- $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
    #- sourceline: 'ppa:ubuntu-toolchain-r/test'
    #- sourceline: 'ppa:jonathonf/gcc'
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    #- gcc-9
    #- g++-9
    - clang-9
    #- postgresql
    #- postgresql-server-dev-10
  #homebrew:
    #packages:
    #- llvm@7
    #- bison
    #- flex
    
#before_cache:
  #- brew cleanup
  
before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  #- sudo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
  #- sudo deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
  #- sudo apt install clang-9

  - if [[ $LINUX ]]; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-linux-client.tar.gz; fi
  - if [[ $OSX ]]  ; then curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-macos-client.tar.gz; fi
  - tar -xvf sw.tar.gz
  - chmod 755 sw
  
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - if [[ $OSX ]]  ; then brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/llvm.rb; fi
  - if [[ $OSX ]]  ; then brew install bison; fi
  - if [[ $OSX ]]  ; then brew install flex; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/bison/bin:$PATH"; fi
  - if [[ $OSX ]]  ; then export PATH="/usr/local/opt/flex/bin:$PATH"; fi
  
  #- sudo sed -i "329a noexcept" /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  #- sudo sed -i "355a noexcept" /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  #- sudo sed -i "359a noexcept" /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  #- sudo sed -i "639a noexcept" /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  #- sudo sed -i "1352s/;/ noexcept;/" /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  
  #- wget https://raw.githubusercontent.com/gcc-mirror/gcc/master/libstdc%2B%2B-v3/include/std/variant
  #- sudo cp variant /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  #- cat /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/variant
  
script:
  #- true
  - ./sw -checks-st -v build
