language: cpp

notifications:
  email: false

#sudo: required
dist: xenial
osx_image: xcode9.2

os:
  - linux
  #- osx

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.sw

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - postgresql
    #- postgresql-server-dev-10

before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  - curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/client_linux.tar.gz
  - tar -xvf sw.tar.gz

  #- if [[ $LINUX ]]; then sudo apt-get update; fi
  #- if [[ $LINUX ]]; then wget --no-check-certificate http://www.cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh; fi
  #- if [[ $LINUX ]]; then sudo sh cmake-3.11.0-Linux-x86_64.sh --skip-license --prefix=/usr; fi
  #- wget -O master.zip https://github.com/cppan/tests/archive/master.zip
  #- unzip master.zip -d .
  #- if [[ $LINUX ]]; then wget https://cppan.org/client/cppan-master-Linux-client.deb; fi
  #- if [[ $LINUX ]]; then sudo dpkg -i cppan-master-Linux-client.deb; fi

  #- if [[ $OSX ]]; then brew upgrade cmake; fi
  - if [[ $OSX ]]; then wget https://cppan.org/client/cppan-master-macOS-client.zip; fi
  - if [[ $OSX ]]; then unzip cppan-master-macOS-client.zip; fi
  - if [[ $OSX ]]; then sudo mv cppan /usr/local/bin/cppan; fi

script:
  - ./sw build
