image: Visual Studio 2017

platform:
  - Win32
  #- Win64

cache:
  - c:/Users/appveyor/.sw

configuration:
  - Release

# for curl
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

before_build:
  - if %platform%==Win32 set winplatform=Win32
  - if %platform%==Win64 set winplatform=Win64

  - curl -fsS -L -o cppan.zip https://github.com/SoftwareNetwork/binaries/raw/master/client.zip
  - 7z x cppan.zip
  - set PATH=%PATH%;%cd%

build_script:
  - client build sw.cpp

#artifacts:
  #- path: bin
  #- path: build
    #name: primitives-$(APPVEYOR_BUILD_VERSION)
