image: Visual Studio 2017

platform:
  - Win32
  #- Win64

cache:
  - c:/Users/appveyor/.sw

configuration:
  - Release

# for curl
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

before_build:
  - if %platform%==Win32 set generator=Visual Studio 15 2017
  - if %platform%==Win64 set generator=Visual Studio 15 2017 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

  - curl -fsS -L -o cppan.zip https://github.com/SoftwareNetwork/binaries/raw/master/client.zip
  - 7z x cppan.zip
  - set PATH=%PATH%;%cd%

build_script:
  #- tree "C:/Program Files (x86)/Windows Kits/10/include"
  - client -s build sw.cpp || echo 0
  #- bin\\main.exe

#test_script:
#  - bin\testxxx

#artifacts:
  #- path: bin
  #- path: build
    #name: primitives-$(APPVEYOR_BUILD_VERSION)
