version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Update package db
          command: apt update
          
      - run:
          name: Install packages
          command: apt install -y curl flex bison g++-8

      - run:
          name: Download SW
          command: curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-linux-client.tar.gz

      - run:
          name: Unpack
          command: tar -xvf sw.tar.gz
          
      - run:
          name: Build
          command: ./sw build
