version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt install curl

      - run:
          name: Download SW
          command: curl -fsS -L -o sw.tar.gz https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-linux-client.tar.gz

      - run:
          name: Unpack
          command: tar -xvf sw.tar.gz
          
      - run:
          name: Build
          command: sw build
