name: sw

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macos-11.0]

    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master

    - name: Install (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install flex bison

    - name: Install (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install flex bison

    - name: build (non macOS)
      if: runner.os != 'macOS'
      run: ./sw build

    - name: build (macOS)
      if: runner.os == 'macOS'
      run: |
        export PATH="/usr/local/opt/flex/bin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        ./sw build

    - name: test
      run: ./sw test
