name: sw

on: [push]

jobs:
  win_and_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-12]

    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master

    - name: Install (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install flex bison

    - name: Install (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install flex bison

    - name: build (non macOS)
      if: runner.os != 'macOS'
      run: ./sw build

    - name: build (macOS)
      if: runner.os == 'macOS'
      run: |
        export PATH="/usr/local/opt/flex/bin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        ./sw build

    - name: test
      run: ./sw test

  linux:
    runs-on: ubuntu-20.04
    container: fedora:36
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install flex bison cmake which gcc clang clang-tools-extra lld git \
          mesa-libGL-devel mesa-libEGL-devel
    - uses: egorpugin/sw-action@master
    - run: ./sw build -compiler gcc

    - name: test
      run: ./sw test
