name: C/C++ CI with SW

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest]
        #os: [windows-latest, ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    #- uses: egorpugin/sw-action@master      
    
    - name: Download SW
      shell: cmake -P {0}
      run: |
        if (WIN32)
          file(DOWNLOAD "https://software-network.org/client/sw-master-windows-client.zip" ./sw.zip)
        elseif (APPLE)
          file(DOWNLOAD "https://software-network.org/client/sw-master-macos-client.tar.gz" ./sw.zip)
        else()
          file(DOWNLOAD "https://software-network.org/client/sw-master-linux-client.tar.gz" ./sw.zip)
        endif()
        
    - name: Unpack SW
      run: cmake -E tar xvf sw.zip
      
    - name: chmod
      run: chmod 755 sw
      shell: sh

    - name: SW Cache
      uses: actions/cache@v1
      with:
        path: ~/.sw
        key: ${{ runner.os }}-sw-storage
        
    - name: build
      run: ./sw build
