name: windows

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest]
        #os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master

    - name: build
      run: ./sw build

    - name: test
      run: ./sw test
