name: C/C++ CI with SW

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Download SW
      shell: cmake -P {0}
      run: |
        file(DOWNLOAD "https://software-network.org/client/sw-master-windows-client.zip" ./sw.zip SHOW_PROGRESS)
      
    - name: Download Qt
      run: cmake -E tar xvf sw.zip
        
    - name: build
      run: ./sw build
