name: sw

on:
  push:
  pull_request:
  schedule:
    # every day
    - cron: 0 0 * * *

jobs:
  windows:
    runs-on: windows-2022    
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: build
      run: ./sw build
    - name: test
      run: ./sw test

  linux:
    runs-on: ubuntu-22.04
    container: fedora:latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install flex bison cmake which gcc clang clang-tools-extra lld git \
          mesa-libGL-devel mesa-libEGL-devel libbsd-devel
    - uses: egorpugin/sw-action@master
    - name: build
      run: ./sw build -compiler gcc
    - name: test
      run: ./sw test
      
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: install
      run: brew install flex bison gcc m4
    - run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - name: build
      run: |
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
        export PATH="/opt/homebrew/opt/flex/bin:$PATH"
        export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
        export PATH="/opt/homebrew/opt/gcc/bin:$PATH"
        ./sw build -compiler gcc-14
    - name: test
      run: |
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
        export PATH="/opt/homebrew/opt/flex/bin:$PATH"
        export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
        export PATH="/opt/homebrew/opt/gcc/bin:$PATH"
        ./sw test -compiler gcc-14
